#!/bin/bash

echo "=== ASR Selection Feature Demo ==="
echo ""

echo "## 功能概述"
echo "ASR選擇模式允許LLM比較Canary和Whisper的ASR結果，"
echo "選擇更好的那個結果進入下一個處理階段，而不是合併它們。"
echo ""

echo "## 兩種模式對比"
echo ""
echo "### 1. 合併模式 (Multi-ASR Comparison)"
echo "  - 開關: --enable_multi_asr_comparison"
echo "  - 行為: LLM合併兩個ASR結果"
echo "  - 輸出: 單一合併後的轉錄"
echo ""

echo "### 2. 選擇模式 (ASR Selection) - 新功能"
echo "  - 開關: --enable_asr_selection"
echo "  - 行為: LLM選擇更好的ASR結果"
echo "  - 輸出: 選擇的轉錄 + CSV報告"
echo ""

echo "## 使用方法"
echo ""

echo "### 基本用法"
echo "啟用ASR選擇模式："
echo "./run_llm_pipeline.sh \\"
echo "  --input_dir /path/to/asr/results \\"
echo "  --output_dir /path/to/output \\"
echo "  --enable_asr_selection \\"
echo "  --medical_correction_model gpt-oss-20b"
echo ""

echo "### 自定義Prompt"
echo "使用自定義的ASR選擇prompt："
echo "./run_llm_pipeline.sh \\"
echo "  --input_dir /path/to/asr/results \\"
echo "  --output_dir /path/to/output \\"
echo "  --enable_asr_selection \\"
echo "  --asr_selection_prompt 'Your custom prompt here' \\"
echo "  --medical_correction_model gpt-oss-20b"
echo ""

echo "## 輸出結構"
echo ""

echo "### 1. 選擇的轉錄文件"
echo "  - 位置: \$OUTPUT_DIR/medical_corrected/"
echo "  - 格式: 與原始文件名相同，但內容是選擇的ASR結果"
echo ""

echo "### 2. CSV報告文件"
echo "  - 位置: \$OUTPUT_DIR/medical_corrected/asr_selection_results.csv"
echo "  - 內容:"
echo "    - filename: 文件名"
echo "    - selected_asr: 選擇的ASR (canary/whisper)"
echo "    - reason: 選擇原因"
echo "    - accuracy_score: 準確性評分 (1-10)"
echo "    - completeness_score: 完整性評分 (1-10)"
echo "    - medical_terminology_score: 醫療術語評分 (1-10)"
echo ""

echo "## CSV報告示例"
echo ""
echo "filename,selected_asr,reason,accuracy_score,completeness_score,medical_terminology_score"
echo "call_001.txt,whisper,Whisper provided more complete medical terminology and clearer context,8,9,9"
echo "call_002.txt,canary,Canary captured more accurate drug names and dosages,9,7,8"
echo "call_003.txt,whisper,Whisper had better overall clarity and completeness,7,8,7"
echo ""

echo "## Prompt模板"
echo ""
echo "ASR選擇使用的prompt模板："
echo ""
echo "You are an expert medical transcription specialist evaluating two ASR transcriptions..."
echo "EVALUATION CRITERIA:"
echo "1. Accuracy: Which transcription more accurately captures the spoken words?"
echo "2. Completeness: Which transcription includes more complete information?"
echo "3. Medical Terminology: Which transcription has better medical term recognition?"
echo "4. Clarity: Which transcription is clearer and more readable?"
echo "5. Context: Which transcription better maintains the EMS communication context?"
echo ""
echo "OUTPUT FORMAT:"
echo "Return a JSON object with:"
echo "- selected_asr: \"canary\" or \"whisper\""
echo "- reason: brief explanation"
echo "- accuracy_score: 1-10"
echo "- completeness_score: 1-10"
echo "- medical_terminology_score: 1-10"
echo ""

echo "## 與現有功能的兼容性"
echo ""
echo "✅ 與多ASR比較模式互斥（只能啟用其中一個）"
echo "✅ 與信息提取功能完全兼容"
echo "✅ 與增強處理功能完全兼容"
echo "✅ 支持自動檢測多ASR結果"
echo "✅ 支持所有LLM模型"
echo ""

echo "## 最佳實踐"
echo ""
echo "1. **選擇標準**: 根據您的具體需求調整prompt中的評估標準"
echo "2. **模型選擇**: 使用較大的模型（如gpt-oss-120b）獲得更好的判斷"
echo "3. **批量處理**: 支持批量處理多個文件"
echo "4. **錯誤處理**: 包含fallback機制，確保處理不會中斷"
echo "5. **報告分析**: 定期分析CSV報告以優化選擇策略"
echo ""

echo "## 測試建議"
echo ""
echo "1. 先用小批量數據測試"
echo "2. 檢查CSV報告的合理性"
echo "3. 比較選擇結果與合併結果的質量"
echo "4. 根據實際效果調整prompt"
echo ""

echo "=== Demo完成 ==="
